name: market-intelligence
role: "Scans X/Twitter for OpenClaw ecosystem updates and generates weekly market intelligence summaries"
llm: minimax/MiniMax-M2.5
reports_to: ceo
trigger: weekly
created_by: cto_proposal
created_at: "2026-02-16T22:56:08.799Z"
context_files:
  - docs/learnings.md
