name: execution-watchdog
role: "Monitors orchestrator execution pipeline and alerts when tasks stall after approval"
llm: minimax/MiniMax-M2.5
reports_to: ceo
trigger: every_sprint
created_by: cto_proposal
created_at: "2026-02-15T16:36:17.897Z"
context_files:
  - docs/learnings.md
