name: pipeline-health-monitor
role: "Monitors orchestrator pipeline health, detects execution stalls, auto-restarts PM2 processes, and alerts on failures"
llm: minimax/MiniMax-M2.5
reports_to: ceo
trigger: every_sprint
created_by: cto_proposal
created_at: "2026-02-15T14:53:46.792Z"
context_files:
  - docs/learnings.md
